image: node:8.5.0

stages:
  - production

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rp-usuarios --api-key=406cd58c-8726-4f48-8d5d-f7d9aa893890
  only:
    - master
